import type { CteListinoOffer } from "@/lib/cte-listino-shared";

function n(months: number | null, extra: string[]): string {
  const bits = [
    months != null ? `Durata offerta: ${months === 0 ? "indeterminata" : `${months} mesi`}.` : null,
    ...extra,
  ].filter((x): x is string => Boolean(x));
  return bits.join(" ");
}

const OPS = {
  full: "Operazioni: switch, subentri, attivazioni, nuovi allacci.",
  fullVoltura: "Operazioni: switch, subentri, attivazioni, nuovi allacci, volture e cambio offerta.",
  switchAttivCambio: "Operazioni: switch, nuove attivazioni e cambio offerta.",
  switchOnly: "Operazioni: solo switch.",
  noAllaccio: "Operazioni: switch, subentri, attivazioni, volture e cambio offerta.",
};

function base(
  partial: Omit<CteListinoOffer, "supplierName" | "category" | "ccvMonthly" | "powerKwMin" | "powerKwMax" | "annualConsumptionMin" | "annualConsumptionMax" | "validFrom" | "validTo">,
): CteListinoOffer {
  return {
    supplierName: "Iren",
    category: "RESIDENZIALE",
    ccvMonthly: null,
    powerKwMin: null,
    powerKwMax: null,
    annualConsumptionMin: null,
    annualConsumptionMax: null,
    validFrom: null,
    validTo: null,
    ...partial,
  };
}

/** PDF OFFERTE SEV-9 — domestiche SEV Iren. */
export const SEV_IREN_LISTINO: CteListinoOffer[] = [
  base({
    offerName: "SEV 13X24 PREZZO FISSO LUCE",
    utility: "LUCE",
    commercialSegment: null,
    priceKind: "FISSO",
    bands: [{ timeBand: "MONO", energyPrice: 0.13 }],
    spread: null,
    ccvAnnual: 155.88,
    networkLosses: "INCLUDED",
    notes: n(24, ["Prezzo fisso 0,13 €/kWh (perdite incluse).", OPS.full]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN QUICK LUCE",
    utility: "LUCE",
    commercialSegment: null,
    priceKind: "FISSO",
    bands: [{ timeBand: "MONO", energyPrice: 0.135 }],
    spread: null,
    ccvAnnual: 149,
    networkLosses: "INCLUDED",
    notes: n(24, ["Prezzo fisso 0,135 €/kWh (perdite incluse).", OPS.fullVoltura]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN QUICK GAS",
    utility: "GAS",
    commercialSegment: null,
    priceKind: "FISSO",
    bands: [{ timeBand: "MONO", energyPrice: 0.63 }],
    spread: null,
    ccvAnnual: 149,
    networkLosses: "NOT_APPLICABLE",
    notes: n(24, ["Prezzo fisso 0,63 €/Smc.", OPS.fullVoltura]),
    warnings: [],
  }),
  base({
    offerName: "SEV SUMMER LUCE",
    utility: "LUCE",
    commercialSegment: null,
    priceKind: "VARIABILE",
    bands: [],
    spread: 0,
    ccvAnnual: 119,
    networkLosses: "INCLUDED",
    notes: n(12, [
      "Prezzo: PUN (maggiorazione non stampata → spread 0).",
      OPS.switchAttivCambio,
      "Fatturazione bimestrale per potenze inferiori a 15 kW.",
    ]),
    warnings: ["Listino: solo «PUN», senza +X — spread impostato a 0, non inventato un altro valore."],
  }),
  base({
    offerName: "SEV SUMMER GAS",
    utility: "GAS",
    commercialSegment: null,
    priceKind: "VARIABILE",
    bands: [],
    spread: 0,
    ccvAnnual: 119,
    networkLosses: "NOT_APPLICABLE",
    notes: n(12, [
      "Prezzo: PSV (maggiorazione non stampata → spread 0).",
      OPS.switchAttivCambio,
      "Fatturazione bimestrale per consumi inferiori a 5000 Smc/anno.",
    ]),
    warnings: ["Listino: solo «PSV», senza +X — spread impostato a 0, non inventato un altro valore."],
  }),
  base({
    offerName: "SEV IREN BONUS 100 LUCE",
    utility: "LUCE",
    commercialSegment: null,
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.0165,
    ccvAnnual: 200,
    networkLosses: "INCLUDED",
    notes: n(12, [
      "Spread: PUN + 0,0165 €/kWh.",
      OPS.fullVoltura,
      "Bonus 100 € accreditato sulla bolletta del 12° mese.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN BONUS 100 GAS",
    utility: "GAS",
    commercialSegment: null,
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 200,
    networkLosses: "NOT_APPLICABLE",
    notes: n(12, [
      "Spread: PSV + 0,15 €/Smc.",
      OPS.fullVoltura,
      "Bonus 100 € accreditato sulla bolletta del 12° mese.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV FULL ENERGY LUCE SPECIAL EDITION",
    utility: "LUCE",
    commercialSegment: "SPECIAL EDITION",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.0165,
    ccvAnnual: 144,
    networkLosses: "INCLUDED",
    notes: n(12, [
      "Spread: PUN + 0,0165 €/kWh.",
      "Operazioni: switch, subentri, attivazioni, nuovi allacci, volture, voltura con switch e cambio offerta.",
      "Obbligo RID e bolletta web in caso di voltura con switch.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV FULL ENERGY GAS SPECIAL EDITION",
    utility: "GAS",
    commercialSegment: "SPECIAL EDITION",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 144,
    networkLosses: "NOT_APPLICABLE",
    notes: n(12, [
      "Spread: PSV + 0,15 €/Smc.",
      "Operazioni: switch, subentri, attivazioni, nuovi allacci, volture, voltura con switch e cambio offerta.",
      "Obbligo RID e bolletta web in caso di voltura con switch.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN X VULNERABILI STG",
    utility: "LUCE",
    commercialSegment: "VULNERABILI STG",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0,
    ccvAnnual: 35,
    networkLosses: "INCLUDED",
    notes: n(12, [
      "Prezzo: PUN (maggiorazione non stampata → spread 0).",
      OPS.switchOnly,
      "Solo clienti over 75 nel mercato libero, o clienti vulnerabili in STG non con SEV Iren.",
    ]),
    warnings: ["Listino: solo «PUN», senza +X — spread impostato a 0."],
  }),
  base({
    offerName: "SEV GAS TUTELA VULNERABILITÀ",
    utility: "GAS",
    commercialSegment: "TUTELA VULNERABILITÀ",
    priceKind: "VARIABILE",
    bands: [],
    spread: null,
    ccvAnnual: 55.39,
    networkLosses: "NOT_APPLICABLE",
    notes: n(0, [
      "Indice: CMEMm (non è uno spread PSV). Completa lo spread a mano se serve in form.",
      OPS.switchOnly,
      "Clienti vulnerabili: over 75, legge 104, condizioni economiche svantaggiate, utenze di emergenza da eventi calamitosi.",
    ]),
    warnings: ["Prezzo CMEMm: spread non presente nel PDF, non inventato."],
  }),
  base({
    offerName: "SEV BONUS 60 GAS EXCLUSIVE",
    utility: "GAS",
    commercialSegment: "EXCLUSIVE",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 139,
    networkLosses: "NOT_APPLICABLE",
    notes: n(12, [
      "Spread: PSV + 0,15 €/Smc.",
      OPS.switchOnly,
      "Bonus 5 €/mese per 12 mesi. Solo switch e clienti con POD in STG.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN LUCE PERTINENZE",
    utility: "LUCE",
    commercialSegment: "PERTINENZA / ALTRI USI",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.049,
    ccvAnnual: 240,
    networkLosses: "INCLUDED",
    notes: n(12, ["Spread: PUN + 0,049 €/kWh.", OPS.noAllaccio, "Offerta per altri usi in codice fiscale."]),
    warnings: [],
  }),
  base({
    offerName: "SEV REVOLUTION SALUTE LUCE VARIABILE",
    utility: "LUCE",
    commercialSegment: "REVOLUTION",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.027,
    ccvAnnual: 162,
    networkLosses: "INCLUDED",
    notes: n(24, [
      "Spread: PUN + 0,027 €/kWh.",
      OPS.fullVoltura,
      "Inclusa polizza assistenza sanitaria; in switch out si risolve anche la polizza.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV REVOLUTION SPESE PROTETTE GAS VARIABILE",
    utility: "GAS",
    commercialSegment: "REVOLUTION",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 162,
    networkLosses: "NOT_APPLICABLE",
    notes: n(24, [
      "Spread: PSV + 0,15 €/Smc.",
      OPS.fullVoltura,
      "Inclusa polizza perdite pecuniarie; in switch out si risolve anche la polizza.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN LUCE CONNETTIVITA",
    utility: "LUCE",
    commercialSegment: "CONNETTIVITÀ",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.0275,
    ccvAnnual: 169,
    networkLosses: "INCLUDED",
    notes: n(24, [
      "Spread: PUN + 0,0275 €/kWh.",
      OPS.fullVoltura,
      "Fibra: 18,99 € per 12 mesi, poi 20,99 €. Obbligo RID e fattura web.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN GAS CONNETTIVITA",
    utility: "GAS",
    commercialSegment: "CONNETTIVITÀ",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 169,
    networkLosses: "NOT_APPLICABLE",
    notes: n(24, [
      "Spread: PSV + 0,15 €/Smc.",
      OPS.fullVoltura,
      "Fibra: costo attivazione 49,99 €; 18,99 € per 12 mesi, poi 20,99 €. Obbligo RID e fattura web.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN SMALL LUCE MULTISERVIZI",
    utility: "LUCE",
    commercialSegment: "MULTISERVIZI",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.027,
    ccvAnnual: 144,
    networkLosses: "INCLUDED",
    notes: n(24, [
      "Spread: PUN + 0,027 €/kWh.",
      OPS.noAllaccio,
      "Interventi tecnici, costo 4 €/mese. Obbligo RID e fattura web.",
    ]),
    warnings: [],
  }),
  base({
    offerName: "SEV IREN SMALL GAS MULTISERVIZI",
    utility: "GAS",
    commercialSegment: "MULTISERVIZI",
    priceKind: "VARIABILE",
    bands: [],
    spread: 0.15,
    ccvAnnual: 144,
    networkLosses: "NOT_APPLICABLE",
    notes: n(24, [
      "Spread: PSV + 0,15 €/Smc.",
      OPS.noAllaccio,
      "Interventi tecnici, costo 4 €/mese. Obbligo RID e fattura web.",
    ]),
    warnings: [],
  }),
];

export function isSevIrenListinoText(text: string): boolean {
  const t = text.replace(/\s+/g, " ");
  return /SEV 13X24/i.test(t) && /SEV IREN\s+QUICK/i.test(t) && /OFFERTE SEV/i.test(t);
}
