import type { CteListinoOffer } from "@/lib/cte-listino-shared";

const LOSSES_NOTE = "Perdite di rete escluse (come da tabella). CCV non indicata nello screenshot.";
const WINDOW = "Finestra commerciale Smart People: 15–28 settembre 2026.";

function note(extra: string[]): string {
  return [...extra, WINDOW, LOSSES_NOTE].join(" ");
}

const EMPTY = {
  ccvAnnual: null,
  ccvMonthly: null,
  spread: null,
  validFrom: "2026-09-15" as const,
};

/** CTE Corporate Power a prezzo fisso — screenshot 15-28 settembre 2026. */
export const ENEL_CORPORATE_LISTINO: CteListinoOffer[] = [
  {
    ...EMPTY,
    supplierName: "Enel",
    offerName: "ENEL BUSINESS SUPER LUCE",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MICRO",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1845 },
      { timeBand: "F2", energyPrice: 0.1855 },
      { timeBand: "F3", energyPrice: 0.1855 },
    ],
    powerKwMin: 3,
    powerKwMax: 25,
    annualConsumptionMin: null,
    annualConsumptionMax: 1_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-10-01",
    notes: note(["Validità offerta fino al 01/10/2026."]),
    warnings: [],
  },
  {
    ...EMPTY,
    supplierName: "Soluzione Energia",
    offerName: "SOLUZIONE ENERGIA IMPRESA PMI",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC SMALL",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1897 },
      { timeBand: "F2", energyPrice: 0.204 },
      { timeBand: "F3", energyPrice: 0.173 },
    ],
    powerKwMin: 25,
    powerKwMax: 49,
    annualConsumptionMin: null,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note([]),
    warnings: [],
  },
  {
    ...EMPTY,
    supplierName: "Soluzione Energia",
    offerName: "SOLUZIONE ENERGIA IMPRESA",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MEDIUM A",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1875 },
      { timeBand: "F2", energyPrice: 0.2027 },
      { timeBand: "F3", energyPrice: 0.1707 },
    ],
    powerKwMin: 50,
    powerKwMax: 199,
    annualConsumptionMin: null,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note([]),
    warnings: [],
  },
  {
    ...EMPTY,
    supplierName: "Enel",
    offerName: "ENEL FIDELITY 24",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MEDIUM A",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1681 },
      { timeBand: "F2", energyPrice: 0.1784 },
      { timeBand: "F3", energyPrice: 0.1494 },
    ],
    powerKwMin: 50,
    powerKwMax: 199,
    annualConsumptionMin: null,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note(["Prevista penale."]),
    warnings: [],
  },
  {
    ...EMPTY,
    supplierName: "Soluzione Energia",
    offerName: "SOLUZIONE ENERGIA IMPRESA SUPER",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MEDIUM B",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.18099 },
      { timeBand: "F2", energyPrice: 0.198 },
      { timeBand: "F3", energyPrice: 0.1652 },
    ],
    powerKwMin: 200,
    powerKwMax: null,
    annualConsumptionMin: 500_000,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note(["Potenza da 200 kW (max non indicato)."]),
    warnings: ["Potenza massima non indicata nello screenshot."],
  },
  {
    ...EMPTY,
    supplierName: "Enel",
    offerName: "ENEL FIDELITY 24MT",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MEDIUM B",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1598 },
      { timeBand: "F2", energyPrice: 0.1714 },
      { timeBand: "F3", energyPrice: 0.1422 },
    ],
    powerKwMin: 200,
    powerKwMax: null,
    annualConsumptionMin: null,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note(["Media tensione.", "Prevista penale.", "Potenza da 200 kW (max non indicato)."]),
    warnings: ["Potenza massima non indicata nello screenshot."],
  },
  {
    ...EMPTY,
    supplierName: "Soluzione Energia",
    offerName: "SOLUZIONE ENERGIA NEXT MT",
    utility: "LUCE",
    category: "BUSINESS",
    commercialSegment: "AC MEDIUM B",
    priceKind: "FISSO",
    bands: [
      { timeBand: "F1", energyPrice: 0.1635 },
      { timeBand: "F2", energyPrice: 0.1801 },
      { timeBand: "F3", energyPrice: 0.1496 },
    ],
    powerKwMin: 200,
    powerKwMax: null,
    annualConsumptionMin: null,
    annualConsumptionMax: 4_000_000,
    networkLosses: "EXCLUDED",
    validTo: "2026-09-28",
    notes: note(["Media tensione.", "Potenza da 200 kW (max non indicato)."]),
    warnings: ["Potenza massima non indicata nello screenshot."],
  },
];

/** SHA-256 dello screenshot CTE Corporate Power (settembre 2026). */
export const ENEL_CORPORATE_SCREENSHOT_HASH =
  "5405c79644cf198bafea1aa90c09135a7cefeb907cc4ba5662e362b602e13e81";
